@server = https://jeffersononsihuay-fantastic-computing-wwvjqwgxqgw35jw-8080.preview.app.github.dev/
###
GET {{server}}
###
GET {{server}}/cursos
###
GET {{server}}/cursos/2
###
GET {{server}}/cursos?size=2
###
GET {{server}}/cursos?size=2&page=1
###
GET {{server}}/cursos?sort=nombre,desc
###
GET {{server}}/cursos?sort=nombre,asc
###
GET {{server}}/cursos?sort=creditos,desc
###
POST {{server}}/cursos
Content-Type: application/json

{"nombre": "Compiladores", "creditos": 5}
###
DELETE {{server}}/cursos/102
###
PATCH {{server}}/cursos/55
Content-Type: application/json

{"creditos": 5}

###
GET {{server}}/profile/cursos

###
GET {{server}}/cursos/search/findByNombre?nombre=Inteligencia+Artificial+1

############ Carrera
GET {{server}}/carreras
###
POST {{server}}/carreras
Content-Type: application/json

{"nombre": "Marketing"}
###
GET {{server}}/cursos/2/carrera
###
GET {{server}}/carreras/1
###
GET {{server}}/carreras/1/cursos
###